// flow-typed signature: ef758f417620ee56f2417ea30f3af775
// flow-typed version: <<STUB>>/doc-ready_v^1.0.4/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doc-ready'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doc-ready' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'doc-ready/doc-ready' {
  declare module.exports: any;
}

declare module 'doc-ready/examples/require-js' {
  declare module.exports: any;
}

// Filename aliases
declare module 'doc-ready/doc-ready.js' {
  declare module.exports: $Exports<'doc-ready/doc-ready'>;
}
declare module 'doc-ready/examples/require-js.js' {
  declare module.exports: $Exports<'doc-ready/examples/require-js'>;
}
